
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PickMen?serverTimezone=UTC
    username: root
    password: cjswo1591
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

<<<<<<< HEAD
=======
  servlet:
    multipart:
      location: c:\\upload
      maxFileSize: 200MB
      maxRequestSize: 100MB
  


>>>>>>> a54b9f05b1bab4d24ea6fb96e8cfa5e131f598c5
  mail:
    host: smtp.gmail.com
    port: 587
    username: wocjf0513@ajou.ac.kr  
    password: zcplisaxwurmivii
    properties:
      mail:
        smtp:
          starttls:
<<<<<<< HEAD
            enable: false
            required: true
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
=======
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
>>>>>>> a54b9f05b1bab4d24ea6fb96e8cfa5e131f598c5
