
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PickMen?serverTimezone=UTC
    username: root
    password: '@Altmxpfl12'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: wocjf0513@ajou.ac.kr  
    password: zcplisaxwurmivii
    properties:
      mail:
        smtp:
          starttls:
            enable: false
            required: true
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
